site_name: Citrix NetScaler Ansible Module Documentation
site_description: Documentation for Citrix NetScaler Ansible Modules 0.1
theme_dir: citrix-sdk
markdown_extensions:
  - admonition
  - codehilite
  -  toc:
      anchorlink: true




pages:
  - NetScaler Ansible Docs: index.md
  - User Documentation:
    - Getting Started: usage/getting-started.md
    - Speeding up execution: usage/speeding-up-execution.md
    - Rolling upgrades: usage/rolling-upgrades.md
    - Rolling upgrades (VPX): usage/rolling-upgrades-vpx.md
    - Netscaler ansible docker image: usage/docker-image.md
  - Using Generic Ansible Modules:
    - Using generic Ansible modules: generic-modules/about.md
    - Templating the configuration file: generic-modules/templating-configuration-file.md
    - Direct NITRO API calls: generic-modules/nitro-api-calls.md
  - Module Documentation:
    - Module index: modules/index.md
    - netscaler_cs_action: modules/netscaler-cs-action-module.md 
    - netscaler_cs_policy: modules/netscaler-cs-policy-module.md 
    - netscaler_cs_vserver: modules/netscaler-cs-vserver-module.md
    - netscaler_gslb_service: modules/netscaler-gslb-service-module.md 
    - netscaler_gslb_site: modules/netscaler-gslb-site-module.md
    - netscaler_gslb_vserver: modules/netscaler-gslb-vserver-module.md
    - netscaler_lb_monitor: modules/netscaler-lb-monitor-module.md
    - netscaler_lb_vserver: modules/netscaler-lb-vserver-module.md/
    - netscaler_nitro_request: modules/netscaler-nitro-request-module.md
    - netscaler_save_config: modules/netscaler-save-config-module.md
    - netscaler_server: modules/netscaler-server-module.md
    - netscaler_service: modules/netscaler-service-module.md
    - netscaler_servicegroup: modules/netscaler-servicegroup-module.md
    - netscaler_ssl_certkey: modules/netscaler-ssl-certkey-module.md
  - Developer Documentation: development-utilities.md

